"""将规则列表渲染为带头注释的 Surge .list 文件。

智能时间戳:头注释包含 Updated 时间,但仅在规则内容真正变化时推进。
若本次构建的规则体与已有产物完全一致,则沿用其旧时间戳,使文件字节保持
不变——git 视为无变更,既不产生噪声 commit,也不会引发并发 rebase 冲突。
"""

from __future__ import annotations

import re
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

from .models import Rule

_UPDATED_RE = re.compile(r"^#\s*Updated:\s*(.+?)\s*$")


def _iso_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _extract_body_and_timestamp(text: str) -> tuple[list[str], str | None]:
    """从已有产物中提取 (规则体行, Updated 时间戳)。

    规则体 = 非注释、非空行;时间戳取头注释里的 Updated 值(无则 None)。
    """
    body: list[str] = []
    timestamp: str | None = None
    for line in text.splitlines():
        m = _UPDATED_RE.match(line)
        if m:
            timestamp = m.group(1)
            continue
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        body.append(s)
    return body, timestamp


def _resolve_timestamp(path: Path, new_body: list[str], now: str | None) -> str:
    """决定写入的时间戳。

    规则体与已有产物一致且旧产物带时间戳 -> 沿用旧值(保持字节稳定);
    否则使用当前时间(now 显式传入便于测试)。
    """
    if path.exists():
        old_body, old_ts = _extract_body_and_timestamp(
            path.read_text(encoding="utf-8")
        )
        if old_body == new_body and old_ts is not None:
            return old_ts
    return now if now is not None else _iso_now()


def _header(
    desc: str, sources: list[str], counts: Counter[str], timestamp: str
) -> str:
    total = sum(counts.values())
    lines = [
        "###############################################################",
        "# Generated by surge-ruleset-forge",
        "# https://github.com/qidewei2004/surge-ruleset-forge",
        f"# Description: {desc}",
        f"# Updated: {timestamp}",
        f"# Total: {total}",
    ]
    for rtype in sorted(counts):
        lines.append(f"#   {rtype}: {counts[rtype]}")
    lines.append("# Upstream sources:")
    for s in sources:
        lines.append(f"#   - {s}")
    lines.append("###############################################################")
    return "\n".join(lines)


def emit(
    path: Path,
    rules: list[Rule],
    *,
    desc: str,
    sources: list[str],
    now: str | None = None,
) -> int:
    """写出 .list 文件,返回规则条数。

    now: 显式时间戳(ISO 字符串),仅用于测试注入;生产环境留空取当前时间。
    """
    counts = Counter(r.rtype for r in rules)
    body_lines = [r.render() for r in rules]
    timestamp = _resolve_timestamp(path, body_lines, now)

    body = "\n".join(body_lines)
    content = _header(desc, sources, counts, timestamp) + "\n" + body + "\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return len(rules)
