"""将规则列表渲染为带头注释的 Surge .list 文件。"""

from __future__ import annotations

from collections import Counter
from pathlib import Path

from .models import Rule


def _header(desc: str, sources: list[str], counts: Counter[str]) -> str:
    # 注:头注释不含构建时间戳,使产物成为输入的纯函数——
    # 规则未变则文件字节不变,git 视为无变更,避免噪声 commit 与并发冲突。
    # 更新时间以 git commit 时间为准。
    total = sum(counts.values())
    lines = [
        "###############################################################",
        "# Generated by surge-ruleset-forge",
        "# https://github.com/qidewei2004/surge-ruleset-forge",
        f"# Description: {desc}",
        f"# Total: {total}",
    ]
    for rtype in sorted(counts):
        lines.append(f"#   {rtype}: {counts[rtype]}")
    lines.append("# Upstream sources:")
    for s in sources:
        lines.append(f"#   - {s}")
    lines.append("###############################################################")
    return "\n".join(lines)


def emit(
    path: Path,
    rules: list[Rule],
    *,
    desc: str,
    sources: list[str],
) -> int:
    """写出 .list 文件,返回规则条数。"""
    counts = Counter(r.rtype for r in rules)
    body = "\n".join(r.render() for r in rules)
    content = _header(desc, sources, counts) + "\n" + body + "\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return len(rules)
